In [19]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
from bs4 import BeautifulSoup
import requests
import pandas as pd
import math
print("Importing done")

Importing done

In [20]:
driver = webdriver.Chrome()
url = 'https://itviec.com/sign_in'
driver.get(url)
sleep(3)

In [21]:
credential = open('account.txt')
line = credential.readlines()
username = line[0]
password = line[2]

print('Finish importing the login credentials')

Finish importing the login credentials

In [22]:
# login_button = driver.find_element('xpath', '//*[@id="navbarNavDropdown"]/ul[2]/li[2]/a')
# login_button.click()
# sleep(1)

email_field = driver.find_element('xpath', '//*[@id="user_email"]')
email_field.send_keys(username)
sleep(1)

password_field = driver.find_element('xpath', '//*[@id="user_password"]')
password_field.send_keys(password)
sleep(1)

login_in = driver.find_element('xpath', '//*[@id="container"]/div[3]/div/div[2]/form/div[4]/div/button')
login_in.click()
sleep(3)

In [23]:
try: 
    non_ads = driver.find_element('xpath', '//*[@id="upload-cv-modal"]/div/div/div/button')
    non_ads.click()
except:
    pass

city = driver.find_element('xpath', '//*[@id="search_form"]/div[2]/div/div')
city.click()

all_city = driver.find_element('xpath', '//*[@id="city-ts-control"]')
all_city.click()

key_word = 'data'
search_job = driver.find_element('xpath', '//*[@id="query"]')
search_job.send_keys(key_word)

ran_click = driver.find_element('xpath', '//*[@id="search_form"]/div[4]')
ran_click.click()
sleep(1)
search_button = driver.find_element('xpath', '//*[@id="search_form"]/div[5]')
search_button.click()

In [24]:
number_jobs = driver.find_element('xpath', '//*[@id="jobs"]/h1').text
print(number_jobs)

for s in number_jobs.split():
    if s.isdigit():
        print(s)
        number_of_page = math.ceil(int(s)/20)

print(number_of_page)

tag_h3 = []
cards = []
arr_all_pages = []

for i in range(1,number_of_page+1):
    link_all_pages = f'https://itviec.com/it-jobs/data?job_selected={key_word}&page={i}'
    arr_all_pages.append(link_all_pages)

print(arr_all_pages)

list_names = []
list_links = []

for link_page in arr_all_pages:
    driver.get(link_page)
    requests.get(link_page)
    soup =  BeautifulSoup(driver.page_source)
    tag_h3 = (soup.find_all('h3', 'title job-details-link-wrapper'))
    sleep(1)
    for tag_a in tag_h3:
        tags = tag_a.find(name ='a')
        list_names.append(tags.text.strip())
        list_links.append('https://itviec.com/'+ tags['href'])

15 data jobs in Ha Noi
15
1
['https://itviec.com/it-jobs/data?job_selected=data&page=1']

In [25]:
len(list_links)

20

In [26]:
list_names

['Data Analyst (SQL/Cloud)',
 'Data Annotation Specialist (AI)',
 'Data Engineer (Python, SQL)',
 'Data Analyst (Database, Oracle, PL/SQL, ETL)',
 'Data Analyst (Business Intelligence, SQL, Python)',
 'Chuyên viên Dữ liệu lớn Big Data (Data Analyst, SQL)',
 'Senior Data Analytics / Business Intelligence Engineer',
 'Data Analyst (SQL)',
 'Data Engineer (Data Analyst, SQL, Python)',
 'Data Analyst',
 'Viettel Digital - Data Scientist (Data Analyst, SQL)',
 'Data Analyst/Data Engineer (SQL/ASP.NET/C#)',
 'Senior Data Scientist (Machine Learning)',
 'Business Intelligence Engineer ((BI/Data Analyst/SQL)',
 'Data Engineer (SQL, Python)',
 'Teaching Assistant - Data Science',
 'Power BI Dev (Data Analyst, SQL, AWS)',
 'Data Reporting (SQL, Database)',
 'Senior Data Engineer (SQL, ETL, Python) Upto$2500',
 'Senior Data Engineer']

In [27]:
list_links

['https://itviec.com//it-jobs/data-analyst-sutrix-solutions-2052?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-annotation-specialist-ai-geocomply-geotech-hub-vietnam-4056?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-engineer-python-sql-athena-techhub-0548?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-analyst-database-oracle-pl-sql-etl-kien-long-bank-1721?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-analyst-business-intelligence-sql-python-velacorp-4447?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/chuyen-vien-du-lieu-lon-big-data-data-analyst-sql-brg-group-0508?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/senior-data-analytics-business-intelligence-engineer-van-thiel-co-4839?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-analyst-k-g-viet-nam-3230?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-engineer-database-sql-python-maple-labs-5133?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-analyst-techcombank-0620?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/viettel-digital-data-scientist-data-analyst-sql-viettel-group-3222?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/senior-data-analyst-tpf-vietnam-1152?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/senior-data-scientist-machine-learning-m_service-momo-5900?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/business-intelligence-engineer-orient-software-development-corp-2204?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-engineer-sql-python-got-it-4924?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/teaching-assistant-data-science-coderschool-5535?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/power-bi-dev-data-analyst-sql-aws-flight-centre-travel-group-4158?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/data-reporting-sql-database-lac-viet-computing-corporation-3209?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/senior-data-engineer-sql-etl-python-upto-2500-simple-tech-investment-4320?lab_feature=preview_jd_page',
 'https://itviec.com//it-jobs/senior-data-engineer-ghn-3600?lab_feature=preview_jd_page']

In [28]:
# list name có ở trên
company = []
website_company = []
address_company = []
work_at = []
salary= []
skills_require= []
# list link có ở trên
a=[]

In [29]:
for job_link in list_links:
    driver.get(job_link)
    sleep(3)
    page_source = driver.page_source
    soup =  BeautifulSoup(page_source, 'html.parser')

    try:
        # company.append(driver.find_element('xpath', '//*[@id="container"]/div[3]/div[3]/div/div/div[1]/div[2]/div').text)
        company_names = soup.find_all(name = 'h3', attrs = {'class' : 'employer-long-overview__name hidden-xs d-none d-sm-block'})

        for name in company_names:
            job = name.find('a')
            company.append(job.text.strip())
    except:
        company.append('nan')
    
    try:
        company_website = soup.find_all('h3', 'employer-long-overview__name hidden-xs d-none d-sm-block' )
        for web in company_website:
            website = web.find('a')
            website_company.append('https://itviec.com/'+ website['href'])
        # website_company.append(driver.find_element('xpath', '//*[@id="container"]/div[3]/div[3]/div/div/div[1]/div[2]/h3/a').get_attribute("href"))
    except:
        website_company.append('nan')
    
    try:
        # add = soup.find_all('div','svg-icon')
        # for a in add:
        #     adt = a.find('div','svg-icon__text')
        #     address_company.append(adt.text().strip())
        address_company.append(driver.find_element('xpath', '//*[@id="container"]/div[3]/div[2]/div/div[2]/div[3]/div/span').text)

    except:
        address_company.append('nan')
    
    try:
        # work_where = soup.find_all('div', 'svg-icon__box d-flex align-items-center')
        # for w in work_where:
        #     ww = w.find('div','svg-icon__text')
        #     work_at.append(ww.text.strip())
        work_at.append(driver.find_element('xpath', '//*[@id="container"]/div[3]/div[2]/div/div[2]/div[4]/div/div/span').text)
    except:
        work_at.append('nan')
    

    # try:
    #     # skill_test = soup.find_all('div', 'job-details__tag-list')
    #     skill_test = soup.find_all('a','big ilabel mkt-track').get('span')
    #     # for list_skill in skill_test:
    #     #     a.append(list_skill.get('span'))
    #     skills_require.append(a)
    # except: 
    #     skills_require.append('nan')

    a = []
    page_response = requests.get(job_link)
    page_content = BeautifulSoup(markup=page_response.content, features="html.parser")

    skill_require = page_content.find_all(name = 'a', attrs = {'class' : 'big ilabel mkt-track'})

    for skill in skill_require:
        a.append(skill.text.replace('\n', ''))

    skills_require.append(a)


    try:
        # luong = soup.find_all('div', 'svg-icon svg-icon--rounded svg-icon--green')
        # for s in luong:
        #     sala= s.find('div','svg-icon__text')
        #     salary.append(sala.text.strip())
        salary.append(driver.find_element('xpath', '//*[@id="container"]/div[3]/div[2]/div/div[2]/div[2]/div').text)
    except:
        salary.append('nan')

In [30]:
len(list_names), len(list_links), len(company),len(website_company),len(address_company),len(work_at),len(salary),len(skills_require)

(20, 20, 20, 20, 20, 20, 20, 20)

In [31]:
df =pd.DataFrame({
                  'name_job':list_names,
                  'company':company,
                  'company_website':website_company,
                  'address_company' : address_company,
                  'work_at': work_at,
                  'salary':salary,
                  'skills':skills_require,
                  'link_job': list_links,
                 }, columns = ['name_job', 'company', 'company_website','address_company', 'work_at', 'salary','skills', 'link_job'])

In [32]:
df

,name_job,company,company_website,address_company,work_at,salary,skills,link_job
0,Data Analyst (SQL/Cloud),Sutrix Solutions,https://itviec.com//companies/sutrix-solutions,"., Other, Ha Noi",At office,"1,000 - 1,500 USD","[Data Analyst, SQL, Cloud]",https://itviec.com//it-jobs/data-analyst-sutri...
1,Data Annotation Specialist (AI),GeoComply (GeoTech Hub Vietnam),https://itviec.com//companies/geocomply-geotec...,"Vincom Center Đồng Khởi, 72 Lê Thánh Tôn, Phườ...",At office,You'll love it,"[Data Analyst, Database]",https://itviec.com//it-jobs/data-annotation-sp...
2,"Data Engineer (Python, SQL)",Athena TechHub,https://itviec.com//companies/athena-techhub,nan,nan,nan,"[Python, SQL, Data Analyst]",https://itviec.com//it-jobs/data-engineer-pyth...
3,"Data Analyst (Database, Oracle, PL/SQL, ETL)",Kien Long Bank,https://itviec.com//companies/kien-long-bank,"98, Cach Mang Thang 8 Street, District 3, Ho C...",At office,Thỏa thuận,"[Data Analyst, SQL, Oracle]",https://itviec.com//it-jobs/data-analyst-datab...
4,"Data Analyst (Business Intelligence, SQL, Python)",Velacorp,https://itviec.com//companies/velacorp,"5th Floor, Viglacera Tower, No.1 Thang Long Av...",At office,"800 - 1,000 USD","[Data Analyst, Python, SQL, Fresher Accepted]",https://itviec.com//it-jobs/data-analyst-busin...
5,Chuyên viên Dữ liệu lớn Big Data (Data Analyst...,BRG Group,https://itviec.com//companies/brg-group,"BRG Tower, 198 Tran Quang Khai, Ly Thai To, Ho...",At office,You'll love it,"[Data Analyst, SQL, Oracle]",https://itviec.com//it-jobs/chuyen-vien-du-lie...
6,Senior Data Analytics / Business Intelligence ...,VAN THIEL & CO.,https://itviec.com//companies/van-thiel-co,"Lily 19, 36 Thao Dien,, Thu Duc City, Ho Chi Minh",At office,You'll love it,"[Database, Data Analyst]",https://itviec.com//it-jobs/senior-data-analyt...
7,Data Analyst (SQL),K&G Việt Nam,https://itviec.com//companies/k-g-viet-nam,"Phạm Hùng, Nam Tu Liem, Ha Noi",At office,"700 - 1,500 USD","[Data Analyst, SQL]",https://itviec.com//it-jobs/data-analyst-k-g-v...
8,"Data Engineer (Data Analyst, SQL, Python)",MAPLE LABS,https://itviec.com//companies/maple-labs,"Sarica No. 6 D9 Street, An Loi Dong , Thu Duc ...",At office,You'll love it,"[Data Analyst, Python, SQL]",https://itviec.com//it-jobs/data-engineer-data...
9,Data Analyst,Techcombank,https://itviec.com//companies/techcombank,"Số 23 Lê Duẩn, phường Bến Nghé, District 1, Ho...",At office,"700 - 1,300 USD","[Data Analyst, Python, SQL]",https://itviec.com//it-jobs/data-analyst-techc...
10,Viettel Digital - Data Scientist (Data Analyst...,Viettel Group,https://itviec.com//companies/viettel-group,"Keangnam Landmark Tower 72, Pham Hung, Nam Tu ...",At office,You'll love it,"[Database, SQL, Data Analyst]",https://itviec.com//it-jobs/viettel-digital-da...
11,Data Analyst/Data Engineer (SQL/ASP.NET/C#),TPF Vietnam,https://itviec.com//companies/tpf-vietnam,"Unit D3-1, 3rd floor, Standard Factory D, Lot ...",At office,You'll love it,"[C#, SQL, Data Analyst]",https://itviec.com//it-jobs/senior-data-analys...
12,Senior Data Scientist (Machine Learning),M_Service (MoMo),https://itviec.com//companies/m_service-momo,"6th Floor, Phu My Hung Tower, 08 Hoang Van Tha...",nan,You'll love it,"[Database, Python, Data Analyst]",https://itviec.com//it-jobs/senior-data-scient...
13,Business Intelligence Engineer ((BI/Data Analy...,Orient Software Development Corp.,https://itviec.com//companies/orient-software-...,"364 Cong Hoa, Tan Binh, Ho Chi Minh",nan,You'll love it,"[Data Analyst, Database, SQL]",https://itviec.com//it-jobs/business-intellige...
14,"Data Engineer (SQL, Python)",Got It,https://itviec.com//companies/got-it-2,"9-11 Nguyễn Văn Thủ, ĐaKao, quận 1., District ...",At office,"1,000 - 2,000 USD","[SQL, Python, Data Analyst]",https://itviec.com//it-jobs/data-engineer-sql-...
15,Teaching Assistant - Data Science,CoderSchool,https://itviec.com//companies/coderschool,"Sonatus Building, 15B Le Thanh Ton, Ben Nghe W...",At office,You'll love it,"[Data Analyst, Python]",https://itviec.com//it-jobs/teaching-assistant...
16,"Power BI Dev (Data Analyst, SQL, AWS)",Flight Centre Travel Group,https://itviec.com//companies/flight-centre-tr...,nan,nan,nan,"[Data Analyst, SQL, AWS]",https://itviec.com//it-jobs/power-bi-dev-data-...
17,"Data Reporting (SQL, Database)",Lac Viet Computing Corporation,https://itviec.com//companies/lac-viet-computi...,"23 Nguyen Thi Huynh, Phu Nhuan, Ho Chi Minh",At office,You'll love it,"[SQL, Database]",https://itviec.com//it-jobs/data-reporting-sql...
18,"Senior Data Engineer (SQL, ETL, Python) Upto$2500",Simple Tech Investment,https://itviec.com//companies/simple-tech-inve...,"402 Nguyễn Thị Minh Khai, District 3, Ho Chi Minh",At office,"1,800 - 2,500 USD","[Database, Python, NoSQL]",https://itviec.com//it-jobs/senior-data-engine...
19,Senior Data Engineer,GHN,https://itviec.com//companies/ghn,"3rd Floor, Rivera Park Building, 7/28 Thanh Th...",At office,You'll love it,"[SQL, Database, NoSQL]",https://itviec.com//it-jobs/senior-data-engine...

In [35]:
df =  df.explode('skills')
df

,name_job,company,company_website,address_company,work_at,salary,skills,link_job
0,Data Analyst (SQL/Cloud),Sutrix Solutions,https://itviec.com//companies/sutrix-solutions,"., Other, Ha Noi",At office,"1,000 - 1,500 USD",Data Analyst,https://itviec.com//it-jobs/data-analyst-sutri...
0,Data Analyst (SQL/Cloud),Sutrix Solutions,https://itviec.com//companies/sutrix-solutions,"., Other, Ha Noi",At office,"1,000 - 1,500 USD",SQL,https://itviec.com//it-jobs/data-analyst-sutri...
0,Data Analyst (SQL/Cloud),Sutrix Solutions,https://itviec.com//companies/sutrix-solutions,"., Other, Ha Noi",At office,"1,000 - 1,500 USD",Cloud,https://itviec.com//it-jobs/data-analyst-sutri...
1,Data Annotation Specialist (AI),GeoComply (GeoTech Hub Vietnam),https://itviec.com//companies/geocomply-geotec...,"Vincom Center Đồng Khởi, 72 Lê Thánh Tôn, Phườ...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/data-annotation-sp...
1,Data Annotation Specialist (AI),GeoComply (GeoTech Hub Vietnam),https://itviec.com//companies/geocomply-geotec...,"Vincom Center Đồng Khởi, 72 Lê Thánh Tôn, Phườ...",At office,You'll love it,Database,https://itviec.com//it-jobs/data-annotation-sp...
2,"Data Engineer (Python, SQL)",Athena TechHub,https://itviec.com//companies/athena-techhub,nan,nan,nan,Python,https://itviec.com//it-jobs/data-engineer-pyth...
2,"Data Engineer (Python, SQL)",Athena TechHub,https://itviec.com//companies/athena-techhub,nan,nan,nan,SQL,https://itviec.com//it-jobs/data-engineer-pyth...
2,"Data Engineer (Python, SQL)",Athena TechHub,https://itviec.com//companies/athena-techhub,nan,nan,nan,Data Analyst,https://itviec.com//it-jobs/data-engineer-pyth...
3,"Data Analyst (Database, Oracle, PL/SQL, ETL)",Kien Long Bank,https://itviec.com//companies/kien-long-bank,"98, Cach Mang Thang 8 Street, District 3, Ho C...",At office,Thỏa thuận,Data Analyst,https://itviec.com//it-jobs/data-analyst-datab...
3,"Data Analyst (Database, Oracle, PL/SQL, ETL)",Kien Long Bank,https://itviec.com//companies/kien-long-bank,"98, Cach Mang Thang 8 Street, District 3, Ho C...",At office,Thỏa thuận,SQL,https://itviec.com//it-jobs/data-analyst-datab...
3,"Data Analyst (Database, Oracle, PL/SQL, ETL)",Kien Long Bank,https://itviec.com//companies/kien-long-bank,"98, Cach Mang Thang 8 Street, District 3, Ho C...",At office,Thỏa thuận,Oracle,https://itviec.com//it-jobs/data-analyst-datab...
4,"Data Analyst (Business Intelligence, SQL, Python)",Velacorp,https://itviec.com//companies/velacorp,"5th Floor, Viglacera Tower, No.1 Thang Long Av...",At office,"800 - 1,000 USD",Data Analyst,https://itviec.com//it-jobs/data-analyst-busin...
4,"Data Analyst (Business Intelligence, SQL, Python)",Velacorp,https://itviec.com//companies/velacorp,"5th Floor, Viglacera Tower, No.1 Thang Long Av...",At office,"800 - 1,000 USD",Python,https://itviec.com//it-jobs/data-analyst-busin...
4,"Data Analyst (Business Intelligence, SQL, Python)",Velacorp,https://itviec.com//companies/velacorp,"5th Floor, Viglacera Tower, No.1 Thang Long Av...",At office,"800 - 1,000 USD",SQL,https://itviec.com//it-jobs/data-analyst-busin...
4,"Data Analyst (Business Intelligence, SQL, Python)",Velacorp,https://itviec.com//companies/velacorp,"5th Floor, Viglacera Tower, No.1 Thang Long Av...",At office,"800 - 1,000 USD",Fresher Accepted,https://itviec.com//it-jobs/data-analyst-busin...
5,Chuyên viên Dữ liệu lớn Big Data (Data Analyst...,BRG Group,https://itviec.com//companies/brg-group,"BRG Tower, 198 Tran Quang Khai, Ly Thai To, Ho...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/chuyen-vien-du-lie...
5,Chuyên viên Dữ liệu lớn Big Data (Data Analyst...,BRG Group,https://itviec.com//companies/brg-group,"BRG Tower, 198 Tran Quang Khai, Ly Thai To, Ho...",At office,You'll love it,SQL,https://itviec.com//it-jobs/chuyen-vien-du-lie...
5,Chuyên viên Dữ liệu lớn Big Data (Data Analyst...,BRG Group,https://itviec.com//companies/brg-group,"BRG Tower, 198 Tran Quang Khai, Ly Thai To, Ho...",At office,You'll love it,Oracle,https://itviec.com//it-jobs/chuyen-vien-du-lie...
6,Senior Data Analytics / Business Intelligence ...,VAN THIEL & CO.,https://itviec.com//companies/van-thiel-co,"Lily 19, 36 Thao Dien,, Thu Duc City, Ho Chi Minh",At office,You'll love it,Database,https://itviec.com//it-jobs/senior-data-analyt...
6,Senior Data Analytics / Business Intelligence ...,VAN THIEL & CO.,https://itviec.com//companies/van-thiel-co,"Lily 19, 36 Thao Dien,, Thu Duc City, Ho Chi Minh",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/senior-data-analyt...
7,Data Analyst (SQL),K&G Việt Nam,https://itviec.com//companies/k-g-viet-nam,"Phạm Hùng, Nam Tu Liem, Ha Noi",At office,"700 - 1,500 USD",Data Analyst,https://itviec.com//it-jobs/data-analyst-k-g-v...
7,Data Analyst (SQL),K&G Việt Nam,https://itviec.com//companies/k-g-viet-nam,"Phạm Hùng, Nam Tu Liem, Ha Noi",At office,"700 - 1,500 USD",SQL,https://itviec.com//it-jobs/data-analyst-k-g-v...
8,"Data Engineer (Data Analyst, SQL, Python)",MAPLE LABS,https://itviec.com//companies/maple-labs,"Sarica No. 6 D9 Street, An Loi Dong , Thu Duc ...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/data-engineer-data...
8,"Data Engineer (Data Analyst, SQL, Python)",MAPLE LABS,https://itviec.com//companies/maple-labs,"Sarica No. 6 D9 Street, An Loi Dong , Thu Duc ...",At office,You'll love it,Python,https://itviec.com//it-jobs/data-engineer-data...
8,"Data Engineer (Data Analyst, SQL, Python)",MAPLE LABS,https://itviec.com//companies/maple-labs,"Sarica No. 6 D9 Street, An Loi Dong , Thu Duc ...",At office,You'll love it,SQL,https://itviec.com//it-jobs/data-engineer-data...
9,Data Analyst,Techcombank,https://itviec.com//companies/techcombank,"Số 23 Lê Duẩn, phường Bến Nghé, District 1, Ho...",At office,"700 - 1,300 USD",Data Analyst,https://itviec.com//it-jobs/data-analyst-techc...
9,Data Analyst,Techcombank,https://itviec.com//companies/techcombank,"Số 23 Lê Duẩn, phường Bến Nghé, District 1, Ho...",At office,"700 - 1,300 USD",Python,https://itviec.com//it-jobs/data-analyst-techc...
9,Data Analyst,Techcombank,https://itviec.com//companies/techcombank,"Số 23 Lê Duẩn, phường Bến Nghé, District 1, Ho...",At office,"700 - 1,300 USD",SQL,https://itviec.com//it-jobs/data-analyst-techc...
10,Viettel Digital - Data Scientist (Data Analyst...,Viettel Group,https://itviec.com//companies/viettel-group,"Keangnam Landmark Tower 72, Pham Hung, Nam Tu ...",At office,You'll love it,Database,https://itviec.com//it-jobs/viettel-digital-da...
10,Viettel Digital - Data Scientist (Data Analyst...,Viettel Group,https://itviec.com//companies/viettel-group,"Keangnam Landmark Tower 72, Pham Hung, Nam Tu ...",At office,You'll love it,SQL,https://itviec.com//it-jobs/viettel-digital-da...
10,Viettel Digital - Data Scientist (Data Analyst...,Viettel Group,https://itviec.com//companies/viettel-group,"Keangnam Landmark Tower 72, Pham Hung, Nam Tu ...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/viettel-digital-da...
11,Data Analyst/Data Engineer (SQL/ASP.NET/C#),TPF Vietnam,https://itviec.com//companies/tpf-vietnam,"Unit D3-1, 3rd floor, Standard Factory D, Lot ...",At office,You'll love it,C#,https://itviec.com//it-jobs/senior-data-analys...
11,Data Analyst/Data Engineer (SQL/ASP.NET/C#),TPF Vietnam,https://itviec.com//companies/tpf-vietnam,"Unit D3-1, 3rd floor, Standard Factory D, Lot ...",At office,You'll love it,SQL,https://itviec.com//it-jobs/senior-data-analys...
11,Data Analyst/Data Engineer (SQL/ASP.NET/C#),TPF Vietnam,https://itviec.com//companies/tpf-vietnam,"Unit D3-1, 3rd floor, Standard Factory D, Lot ...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/senior-data-analys...
12,Senior Data Scientist (Machine Learning),M_Service (MoMo),https://itviec.com//companies/m_service-momo,"6th Floor, Phu My Hung Tower, 08 Hoang Van Tha...",nan,You'll love it,Database,https://itviec.com//it-jobs/senior-data-scient...
12,Senior Data Scientist (Machine Learning),M_Service (MoMo),https://itviec.com//companies/m_service-momo,"6th Floor, Phu My Hung Tower, 08 Hoang Van Tha...",nan,You'll love it,Python,https://itviec.com//it-jobs/senior-data-scient...
12,Senior Data Scientist (Machine Learning),M_Service (MoMo),https://itviec.com//companies/m_service-momo,"6th Floor, Phu My Hung Tower, 08 Hoang Van Tha...",nan,You'll love it,Data Analyst,https://itviec.com//it-jobs/senior-data-scient...
13,Business Intelligence Engineer ((BI/Data Analy...,Orient Software Development Corp.,https://itviec.com//companies/orient-software-...,"364 Cong Hoa, Tan Binh, Ho Chi Minh",nan,You'll love it,Data Analyst,https://itviec.com//it-jobs/business-intellige...
13,Business Intelligence Engineer ((BI/Data Analy...,Orient Software Development Corp.,https://itviec.com//companies/orient-software-...,"364 Cong Hoa, Tan Binh, Ho Chi Minh",nan,You'll love it,Database,https://itviec.com//it-jobs/business-intellige...
13,Business Intelligence Engineer ((BI/Data Analy...,Orient Software Development Corp.,https://itviec.com//companies/orient-software-...,"364 Cong Hoa, Tan Binh, Ho Chi Minh",nan,You'll love it,SQL,https://itviec.com//it-jobs/business-intellige...
14,"Data Engineer (SQL, Python)",Got It,https://itviec.com//companies/got-it-2,"9-11 Nguyễn Văn Thủ, ĐaKao, quận 1., District ...",At office,"1,000 - 2,000 USD",SQL,https://itviec.com//it-jobs/data-engineer-sql-...
14,"Data Engineer (SQL, Python)",Got It,https://itviec.com//companies/got-it-2,"9-11 Nguyễn Văn Thủ, ĐaKao, quận 1., District ...",At office,"1,000 - 2,000 USD",Python,https://itviec.com//it-jobs/data-engineer-sql-...
14,"Data Engineer (SQL, Python)",Got It,https://itviec.com//companies/got-it-2,"9-11 Nguyễn Văn Thủ, ĐaKao, quận 1., District ...",At office,"1,000 - 2,000 USD",Data Analyst,https://itviec.com//it-jobs/data-engineer-sql-...
15,Teaching Assistant - Data Science,CoderSchool,https://itviec.com//companies/coderschool,"Sonatus Building, 15B Le Thanh Ton, Ben Nghe W...",At office,You'll love it,Data Analyst,https://itviec.com//it-jobs/teaching-assistant...
15,Teaching Assistant - Data Science,CoderSchool,https://itviec.com//companies/coderschool,"Sonatus Building, 15B Le Thanh Ton, Ben Nghe W...",At office,You'll love it,Python,https://itviec.com//it-jobs/teaching-assistant...
16,"Power BI Dev (Data Analyst, SQL, AWS)",Flight Centre Travel Group,https://itviec.com//companies/flight-centre-tr...,nan,nan,nan,Data Analyst,https://itviec.com//it-jobs/power-bi-dev-data-...
16,"Power BI Dev (Data Analyst, SQL, AWS)",Flight Centre Travel Group,https://itviec.com//companies/flight-centre-tr...,nan,nan,nan,SQL,https://itviec.com//it-jobs/power-bi-dev-data-...
16,"Power BI Dev (Data Analyst, SQL, AWS)",Flight Centre Travel Group,https://itviec.com//companies/flight-centre-tr...,nan,nan,nan,AWS,https://itviec.com//it-jobs/power-bi-dev-data-...
17,"Data Reporting (SQL, Database)",Lac Viet Computing Corporation,https://itviec.com//companies/lac-viet-computi...,"23 Nguyen Thi Huynh, Phu Nhuan, Ho Chi Minh",At office,You'll love it,SQL,https://itviec.com//it-jobs/data-reporting-sql...
17,"Data Reporting (SQL, Database)",Lac Viet Computing Corporation,https://itviec.com//companies/lac-viet-computi...,"23 Nguyen Thi Huynh, Phu Nhuan, Ho Chi Minh",At office,You'll love it,Database,https://itviec.com//it-jobs/data-reporting-sql...
18,"Senior Data Engineer (SQL, ETL, Python) Upto$2500",Simple Tech Investment,https://itviec.com//companies/simple-tech-inve...,"402 Nguyễn Thị Minh Khai, District 3, Ho Chi Minh",At office,"1,800 - 2,500 USD",Database,https://itviec.com//it-jobs/senior-data-engine...
18,"Senior Data Engineer (SQL, ETL, Python) Upto$2500",Simple Tech Investment,https://itviec.com//companies/simple-tech-inve...,"402 Nguyễn Thị Minh Khai, District 3, Ho Chi Minh",At office,"1,800 - 2,500 USD",Python,https://itviec.com//it-jobs/senior-data-engine...
18,"Senior Data Engineer (SQL, ETL, Python) Upto$2500",Simple Tech Investment,https://itviec.com//companies/simple-tech-inve...,"402 Nguyễn Thị Minh Khai, District 3, Ho Chi Minh",At office,"1,800 - 2,500 USD",NoSQL,https://itviec.com//it-jobs/senior-data-engine...
19,Senior Data Engineer,GHN,https://itviec.com//companies/ghn,"3rd Floor, Rivera Park Building, 7/28 Thanh Th...",At office,You'll love it,SQL,https://itviec.com//it-jobs/senior-data-engine...
19,Senior Data Engineer,GHN,https://itviec.com//companies/ghn,"3rd Floor, Rivera Park Building, 7/28 Thanh Th...",At office,You'll love it,Database,https://itviec.com//it-jobs/senior-data-engine...
19,Senior Data Engineer,GHN,https://itviec.com//companies/ghn,"3rd Floor, Rivera Park Building, 7/28 Thanh Th...",At office,You'll love it,NoSQL,https://itviec.com//it-jobs/senior-data-engine...